const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,

  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  UNPROCESSABLE_ENTITY: 422,

  PAYLOAD_TOO_LARGE: 413, // File quá lớn
  UNSUPPORTED_MEDIA_TYPE: 415, // Định dạng file không hợp lệ
  FILE_UPLOAD_FAILED: 420, // Tuỳ chỉnh: Upload thất bại

  INTERNAL_SERVER_ERROR: 500,
  PARTIAL_CONTENT: 206
} as const

export default HTTP_STATUS
